version: '3'

services:
  sqlite:
    build: ./docker/sqlite
    working_dir: /opennpl
    command: python manage.py runserver 0.0.0.0:8080
    ports:
      - 8080:8080
    env_file:
      - ./.env.dev
  postgres:
    build: ./docker/postgres
    working_dir: /opennpl
    command: python manage.py runserver 0.0.0.0:8081
    ports:
      - 8081:8081
    env_file:
      - ./.env.dev